function cellInfo = BusD6()

cellInfo = {...

%% BUS_GNC_ADSCMD
{...
    'BUS_GNC_ADSCMD', ...
    { ...
    {'AdsOnCmd', 1, 'int8', -1, 'real', 'Sample'}; ...
    } ...
}

};

Simulink.Bus.cellToObject(cellInfo)
disp('BusD6 definition finished');